version: '2'
services:
    pegass-postgresql:
        image: postgres:9.6.5
        # volumes:
        #     - ~/volumes/jhipster/Pegass/postgresql/:/var/lib/postgresql/data/
        environment:
            - POSTGRES_USER=Pegass
            - POSTGRES_PASSWORD=
        ports:
            - 5432:5432
